topics:
  - id:      TOPIC_CHANNEL_SERVICE
    name:    ChannelService
  - id:      TOPIC_CHARACTER_STATUS
    name:    CharacterStatusEventService
  - id:      TOPIC_CHANGE_MAP_COMMAND
    name:    ChangeMapCommandService
  - id:      TOPIC_CHANGE_MAP_EVENT
    name:    ChangeMapEventService
  - id:      TOPIC_CHARACTER_CREATED_EVENT
    name:    CharacterCreatedEventService
  - id:      TOPIC_CHARACTER_STATUS
    name:    CharacterStatusEventService
  - id:      TOPIC_CHARACTER_MOVEMENT
    name:    CharacterMovementEventService
  - id:      TOPIC_CHARACTER_EXPERIENCE_EVENT
    name:    CharacterExperienceService
  - id:      TOPIC_CHARACTER_LEVEL_EVENT
    name:    CharacterLevelService
  - id:      TOPIC_ENTER_PORTAL
    name:    EnterPortalService
  - id:      TOPIC_ENABLE_ACTIONS
    name:    EnableActionsService
  - id:      TOPIC_MAP_CHARACTER_EVENT
    name:    MapCharacterEventService
  - id:      TOPIC_CHARACTER_CHANGE_CHANNEL_EVENT
    name:    CharacterChangeChannelEventService
  - id:      TOPIC_MONSTER_EVENT
    name:    MonsterService
  - id:      TOPIC_MONSTER_MOVEMENT
    name:    MonsterMovementService
  - id:      TOPIC_CONTROL_MONSTER_EVENT
    name:    ControlMonsterService
  - id:      TOPIC_MONSTER_DAMAGE
    name:    MonsterDamageService
  - id:      TOPIC_MONSTER_KILLED_EVENT
    name:    MonsterKilledService
  - id:      TOPIC_DROP_EVENT
    name:    DropService
  - id:      TOPIC_CHARACTER_MAP_MESSAGE_EVENT
    name:    CharacterMapMessageEventService
  - id:      TOPIC_DROP_EXPIRE_EVENT
    name:    DropExpiredService
  - id:      TOPIC_CHARACTER_STAT_EVENT
    name:    CharacterStatService
  - id:      TOPIC_ASSIGN_AP_COMMAND
    name:    AssignApService
  - id:      TOPIC_RESERVE_DROP_COMMAND
    name:    ReserveDropCommandService
  - id:      TOPIC_PICKUP_DROP_COMMAND
    name:    PickupDropCommandService
  - id:      TOPIC_DROP_RESERVATION_EVENT
    name:    DropReservationService
  - id:      TOPIC_PICKUP_DROP_EVENT
    name:    PickupDropService
  - id:      TOPIC_PICKED_UP_ITEM
    name:    PickedUpItemService
  - id:      TOPIC_PICKED_UP_NX
    name:    PickedUpNxService
  - id:      TOPIC_GAIN_MESO
    name:    GainMesoService
  - id:      TOPIC_MESO_GAINED
    name:    MesoGainedService
  - id:      TOPIC_CANCEL_DROP_RESERVATION_COMMAND
    name:    CancelDropReservationCommandService
  - id:      TOPIC_INVENTORY_MODIFICATION
    name:    InventoryModificationService
  - id:      TOPIC_SERVER_NOTICE_COMMAND
    name:    ServerNoticeCommandService
  - id:      TOPIC_NPC_TALK_COMMAND
    name:    NpcTalkService
  - id:      TOPIC_START_NPC_CONVERSATION
    name:    StartNpcConversationService
  - id:      TOPIC_CONTINUE_NPC_CONVERSATION
    name:    ContinueNpcConversationService
  - id:      TOPIC_SET_RETURN_TEXT
    name:    SetReturnTextService
  - id:      TOPIC_CHARACTER_SKILL_UPDATE_EVENT
    name:    CharacterSkillUpdateService
  - id:      TOPIC_ASSIGN_SP_COMMAND
    name:    AssignSpService